### ISSUE TITLE
Create spreadsheet solution for volunteers to collect data

### ISSUE THREAD

**Issue by frhino** [sfbrigade/data-covid19-sfbayarea#1]
Not sure if this will be better as 

1) one spreadsheet with all county departments on one tab, 
2) one spreadsheet with a tab for each county, or 
3) a spreadsheet for each county. 

I'll start with 2, but we can iterate if needed.

**Comment by ldtcooper** [comment]
Since we have some third-party county level data now, I don't think we need to manually collect it anymore
