### ISSUE TITLE
Fetch detailed data from sf.data.gov

### ISSUE THREAD

**Issue by elaguerta** [sfbrigade/data-covid19-sfbayarea#15]
1. [Race and Ethnicity](https://data.sfgov.org/COVID-19/COVID-19-Cases-Summarized-by-Race-and-Ethnicity/vqqm-nsqg)
2. [Age and Gender](https://data.sfgov.org/COVID-19/COVID-19-Cases-Summarized-by-Age-Group-and-Gender/sunc-2t3k)
3. [Date Transmission and Dispostion](https://data.sfgov.org/COVID-19/COVID-19-Cases-Summarized-by-Date-Transmission-and/tvq9-ec9w)
4. [Hospitalizations](https://data.sfgov.org/COVID-19/COVID-19-Hospitalizations/nxjg-bhem)
5. [Tests](https://data.sfgov.org/COVID-19/COVID-19-Tests/nfpa-mg4g)

**Comment by elaguerta** [comment]
I am working on writing a python file with functions to fetch these data into json objects, similar to the existing scraper.py. I'm providing some basic aggregation (such as cases grouped by race, ethnicity, age, and gender)

**Comment by frhino** [comment]
@kengoy  [slack message](https://sfbrigade.slack.com/archives/C010X2VM5DL/p1586581167010700?thread_ts=1586558680.007100&cid=C010X2VM5DL) on this: "if we could do data normalization like now https://github.com/sfbrigade/stop-covid19-sfbayarea/blob/master/data/data.json, it would be great! It would be easy to implement it for front end. But I may have to assume each county data has it's own data set in all different format..."
