### ISSUE TITLE
Determine which counties have detailed data

### ISSUE THREAD

**Issue by elaguerta** [sfbrigade/data-covid19-sfbayarea#16]
Especially breakdowns by race, ethnicity, gender, and age. For example, Santa Clara County has a [dashboard](https://www.sccgov.org/sites/phd/DiseaseInformation/novel-coronavirus/Pages/dashboard.aspx) showing cases and deaths by race, ethnicity, gender, age, and deaths by comorbidity. These are not being parsed by the coronadatascraper for this county.

**Comment by elaguerta** [comment]
I'm working on making a spreadsheet listing that data that are available for each county. I'll provide links to the Corona Data Scraper scraper for that county. The purpose of this will be to identify data coverage. We may need to modify the CDS scrapers to grab additional data, or we may need to write them from scratch.

**Comment by frhino** [comment]
@elaguerta would you mind linking to a google doc with your research findings so others can add to it?

**Comment by elaguerta** [comment]
I have started the google doc, here is the link: https://docs.google.com/spreadsheets/d/1fhdF587nhBlychWvmMwPs2PwGy9ffqiH06ZZhEitVfo/edit?usp=sharing
