### ISSUE TITLE
Marin county does not include unknown race/age/gender data

### ISSUE THREAD

**Issue by Mr0grog** [sfbrigade/data-covid19-sfbayarea#162]
The numbers we have for race/ethnicity, age, and gender in Marin are pulled from the charts on [Marin’s dashboard](https://coronavirus.marinhhs.org/surveillance), which do not include unknown race/ethnicities, ages, and genders. For example, race/ethnicities today report as:

| Race/Ethnicity                   | Cases | Case Percent |
| -------------------------------- | ----: | -----------: |
| Hispanic/Latino                  | 3,046 |        59.2% |
| White                            | 1,561 |        30.3% |
| Asian                            |   139 |         2.7% |
| Black/African American           |    91 |         1.8% |
| Native Hawaiian/Pacific Islander |    15 |         0.3% |
| American Indian/Alaska Native    |     7 |         0.1% |
| Multi or Other Race              |   285 |         5.5% |

But if unknowns were included, this would be:

| Race/Ethnicity                   | Cases | Case Percent | Up to |     |
| -------------------------------- | ----: | -----------: | ----: | --- |
| Hispanic/Latino                  | 3,046 |        45.7% | 68.5% | █████████░░░░░ |
| White                            | 1,561 |        23.4% | 46.2% | █████░░░░ |
| Asian                            |   139 |         2.1% | 24.9% | ░░░░░ |
| Black/African American           |    91 |         1.4% | 24.1% | ░░░░░ |
| Native Hawaiian/Pacific Islander |    15 |         0.2% | 23.0% | ░░░░░ |
| American Indian/Alaska Native    |     7 |         0.1% | 22.9% | ░░░░ |
| Multi or Other Race              |   285 |         4.3% | 27.0% | █░░░░░ |
| Unknown                          |  1516 |        22.8% |     - | ████ |

(Where “up to” is the represents the top end of possible values if we knew all the unknowns; e.g. “hispanic/latino” could be anywhere from 45.7% – 68.5%.)

I calculated the above by looking at the total case counts and comparing them to the total among the race/ethnicity counts. We can do the same for ages and genders.

We can also do this for hospitalizations and deaths, but that one gets a little sticky. For cases, hospitalizations, and deaths, we have a point-in-time, “current” count at the top of the dashboard, and we have time series charts lower down. However, those two don’t match up when it comes to hospitalizations and deaths (they do for cases). They are described the same way in both places, so I’m not clear on what the discrepancy is. We need to choose which to go with.

**Comment by nikobooth** [comment]
I'd say representing the below data in our bar chart would be the clearest way (with unknown as its own category). Our tooltips speak to the high % of unknowns in demographic data.

Race/Ethnicity | Cases | Case Percent
-- | -- | --
Hispanic/Latino | 3,046 | 45.7% 
White | 1,561 | 23.4%
Asian | 139 | 2.1%
Black/African American | 91 | 1.4% 
Native Hawaiian/Pacific Islander | 15 | 0.2%
American Indian/Alaska Native | 7 | 0.1%
Multi or Other Race | 285 | 4.3%
Unknown | 1516 | 22.8%
