### ISSUE TITLE
The San Mateo deaths data v2 is missing

### ISSUE THREAD

**Issue by yetesh** [sfbrigade/data-covid19-sfbayarea#171]
**Describe the bug**
The deaths data for San Mateo County in data v2 is missing:
https://github.com/sfbrigade/stop-covid19-sfbayarea/blob/master/data/data.v2.json#L16204

**To Reproduce**
1. Go to data.v2.json file
2. Search for "san_mateo" and check the "deaths" array
3. The deaths array has no elements

**Expected behavior**
To move from data v1 to data v2, we need the cases and deaths information for each county

**Screenshots**
<img width="669" alt="Screen Shot 2021-01-06 at 9 27 55 PM" src="https://user-images.githubusercontent.com/7647787/104231981-87cea000-5404-11eb-9cc8-86d3033da439.png">

**Comment by Mr0grog** [comment]
> We need to sanity-check that the numbers at least roughly match up to what the county is reporting for current deaths, and if so, consider using it to fill in the deaths timeseries for San Mateo.

Checked this last night, and it is reasonable/feasible.
