### ISSUE TITLE
New Data: San Mateo County

### ISSUE THREAD

**Issue by ychoy** [sfbrigade/data-covid19-sfbayarea#20]
County or Counties: San Mateo County
Data source: https://www.smchealth.org/post/san-mateo-county-covid-19-data-0
Output to: ?
Update frequency/time: Last Update April 6th - maybe a weekly basis? It's not clear when they update.

**Comment by elaguerta** [comment]
The live dashboard is at this link: https://www.smchealth.org/post/san-mateo-county-covid-19-data-1

**Comment by rickpr** [comment]
Taking a crack at this - would appreciate input if anyone has experience with scraping PowerBI.

**Comment by rickpr** [comment]
This is now merged by #56 !
