### ISSUE TITLE
Marin County scraper not returning all available case data

### ISSUE THREAD

**Issue by benghancock** [sfbrigade/data-covid19-sfbayarea#206]
The Marin County scraper is only returning case data through February, even though more current case data is available. It looks like (as @Mr0grog suspected) this is due to our failure to paginate through all the returned records. Marin makes its data available through a Socrata Open Data API, and the default limit for the number of results is 1,000. Our script is returning exactly 1,000 results. 

There is currently no paging logic currently defined in our `SocrataApi` class, so fixing this would likely entail constructing that logic. The [Socrata docs](https://dev.socrata.com/docs/paging.html#2.1) spell this out pretty clearly.  The API does not seem to make available a count of the total records; that information is not in the metadata or in the headers. So we may just need to call for more records until getting an empty response.

**Comment by Mr0grog** [comment]
Oh, I think this is a dupe of #203.

**Comment by benghancock** [comment]
D'oh! Not sure how I missed that. I'll close this.
