### ISSUE TITLE
New Data: Contra Costa County

### ISSUE THREAD

**Issue by ychoy** [sfbrigade/data-covid19-sfbayarea#21]
County or Counties: Contra Costa County
Data source: https://www.coronavirus.cchealth.org/dashboard
Output to: ?
Update frequency/time:  Not clear about the frequency. Dashboard says ```Data reported to CCHS as of 4/13/2020 at 11:30 a.m.```

**Comment by elaguerta** [comment]
This is a Qlik sense dashboard. Live Qlik app at this URL: https://dashboard.cchealth.org/sense/app/93b7808b-5a6d-4e9a-9161-ed2eafeb4afc/overview

**Comment by Mr0grog** [comment]
I recently dug into this a little bit to figure out how to pull data from Qlik. Its API is based on WebSockets, and here’s a little class (with example usage) I wrote to use it: https://gist.github.com/Mr0grog/d751e655f0518e371d42ff5616a6d449

Hopefully that’s a good starter for anyone wanting to scrape Contra Costa!
