### ISSUE TITLE
New Data: Marin County

### ISSUE THREAD

**Issue by ychoy** [sfbrigade/data-covid19-sfbayarea#22]
County or Counties: Marin County
Data source: https://coronavirus.marinhhs.org/surveillance
Output to: ?
Update frequency/time: ? Last update on April 13, 2020

**Comment by elaguerta** [comment]
Looks like cumulative numbers are relatively scrapable from html tables. The age, and gender numbers are very buried.

**Comment by kwonangela7** [comment]
@elaguerta did they always have a "Get the Data" link underneath each visualization? It allows us to export the data shown on the visualization as a csv!! :) If I'm not mistaken, I think your email that you sent to them worked!
