### ISSUE TITLE
New Data: Napa County

### ISSUE THREAD

**Issue by ychoy** [sfbrigade/data-covid19-sfbayarea#24]
County or Counties: Napa County
Data source: https://legacy.livestories.com/s/v2/coronavirus-report-for-napa-county-ca/9065d62d-f5a6-445f-b2a9-b7cf30b846dd/
Output to: ? 
Update frequency/time: Updated at 10:30 AM, Monday through Saturday.

**Comment by robinovitch61** [comment]
Happy to grab this issue!

**Comment by robinovitch61** [comment]
Sorry i never followed up on this!

**Comment by ldtcooper** [comment]
@lenatran are you working on this?

**Comment by jorgio-castello** [comment]
Hey, I'm working on this!

**Comment by ldtcooper** [comment]
Awesome! Thanks @jorgio-castello. If you need any help or guidance, go ahead and ask anyone on the team

**Comment by jorgio-castello** [comment]
Thanks! @ldtcooper I appreciate you reaching out, I'm working on this and hoping to get you something tangible soon

**Comment by Mr0grog** [comment]
@1ec5 found an ArcGIS service that Napa is (now? not sure if new) using to provide case data: https://services1.arcgis.com/Ko5rxt00spOfjMqj/ArcGIS/rest/services/CaseDataDemographics/FeatureServer/0

Example of where he’s using it: https://github.com/1ec5/external-data-bot/commit/a95ed41eb199b1447941ceb22f19759169f9540e
