### ISSUE TITLE
Limit news scraper to time range

### ISSUE THREAD

**Issue by Mr0grog** [sfbrigade/data-covid19-sfbayarea#43]
Over on the front-end side, @kengoy noted that we might want to [limit the time range](https://github.com/sfbrigade/stop-covid19-sfbayarea/pull/79#issuecomment-621010886) included in the news feeds we produce:

> Another consideration is we may want to filter only for the new feeds like for the past 1 or 2 weeks instead of showing all the past feeds.

The current SF scraper just takes everything on the first page of news. Instead, [`NewsScraper`](https://github.com/sfbrigade/data-covid19-sfbayarea/blob/ac696a1444649a1187dbda8e2dea5635e2d47953/covid19_sfbayarea/news/base.py#L7-L61) should take a time range or a “from” date to limit what news items get returned.

---

*Update 2020-06-11: Fixed `NewsScraper` link to point at the class’s new location since the code has been refactored a few times.*

**Comment by csaoma** [comment]
Can I be assigned this? I can add a time limit.

**Comment by Mr0grog** [comment]
Sure, go for it! 👍

**Comment by csaoma** [comment]
So I am working on adding a time limit to NewsScraper, but I have a few questions. 

In the future, will NewsScraper be applied to multiple websites? In this case I think we run into the possibility of each website needing to be scraped differently depending on the setup of the specified website. By this logic it may be better to add date limits to individual methods which handle scraping the dates more specifically. In the meantime, it may be better to add a page limit(increasing the data scraped from 1 page to say 10-20). 

Essentially, I am proposing to increase the amount of pages being scraped rather than doing a date check. In the future for each particular website you can add a time limit more specified to the website being scraped.

**Comment by Mr0grog** [comment]
> In the future, will NewsScraper be applied to multiple websites? In this case I think we run into the possibility of each website needing to be scraped differently depending on the setup of the specified website.

Hmmm, I think there may be some miscommunication happening here. It already runs against multiple sites — `NewsScraper` is just the abstract base class that is customized for each site. See:

- [`AlamedaNews`](https://github.com/sfbrigade/data-covid19-sfbayarea/blob/ac696a1444649a1187dbda8e2dea5635e2d47953/covid19_sfbayarea/news/alameda.py#L11)
- [`ContraCostaNews`](https://github.com/sfbrigade/data-covid19-sfbayarea/blob/ac696a1444649a1187dbda8e2dea5635e2d47953/covid19_sfbayarea/news/contra_costa.py#L40)
- [`MarinNews`](https://github.com/sfbrigade/data-covid19-sfbayarea/blob/ac696a1444649a1187dbda8e2dea5635e2d47953/covid19_sfbayarea/news/marin.py#L10)
- [`NapaNews`](https://github.com/sfbrigade/data-covid19-sfbayarea/blob/ac696a1444649a1187dbda8e2dea5635e2d47953/covid19_sfbayarea/news/napa.py#L22)
- [`SanFranciscoNews`](https://github.com/sfbrigade/data-covid19-sfbayarea/blob/ac696a1444649a1187dbda8e2dea5635e2d47953/covid19_sfbayarea/news/san_francisco.py#L11)
- [`SanMateoNews`](https://github.com/sfbrigade/data-covid19-sfbayarea/blob/ac696a1444649a1187dbda8e2dea5635e2d47953/covid19_sfbayarea/news/san_mateo.py#L32)
- [`SantaClaraNews`](https://github.com/sfbrigade/data-covid19-sfbayarea/blob/ac696a1444649a1187dbda8e2dea5635e2d47953/covid19_sfbayarea/news/santa_clara.py#L11)
- [`SolanoNews`](https://github.com/sfbrigade/data-covid19-sfbayarea/blob/ac696a1444649a1187dbda8e2dea5635e2d47953/covid19_sfbayarea/news/solano.py#L14)
- [`SonomaNews`](https://github.com/sfbrigade/data-covid19-sfbayarea/blob/ac696a1444649a1187dbda8e2dea5635e2d47953/covid19_sfbayarea/news/sonoma.py#L10)

What’s needed in `NewsScraper` is a standard way to pass in and store the date range (i.e. add it to `__init()__` and `get_news()`). Then each implementing class needs to use the stored date range to when doing its work. I’m sorry if I didn’t describe that clearly enough.

> In the meantime, it may be better to add a page limit(increasing the data scraped from 1 page to say 10-20).

I’m not sure I’m following here. What’s generally needed is to *reduce* the number of results returned. Scraping more pages from each site (at least for sites where the results are paginated) would only return *more* results. (I *do* think following pagination to allow for more results might also be nice in the future, but from a practical perspective, nobody is asking for that.)

> In the future for each particular website you can add a time limit more specified to the website being scraped.

The actual time limit definitely should *not* have anything to do with what county/website you are generating a news feed for. The goal here is to be able to say “I want a news feed for [county X] that covers [the past Y days].” We can already do the first part:

```sh
$ ./run_scraper_news.sh [county_name]
# e.g:
$ ./run_scraper_news.sh san_francisco
```

And we need to add a way to specify the second part, e.g:

```sh
$ ./run_scraper_news.sh san_francisco --since 2020-06-01

# Or maybe in terms of days, so the CLI args don’t have to be different
# each time we run it. So for 2 weeks:
$ ./run_scraper_news.sh san_francisco --since 14
```

That means parsing the CLI options, creating a way to send them to any instance of `NewsScraper`, and then ultimately making each implementation of `NewsScraper` make use of that information when it does its work.

**Comment by Mr0grog** [comment]
@csaoma Just checking in — have you made any progress on this, or do you need any help with it?

**Comment by csaoma** [comment]
I haven't made much progress on this recently due to my busy work schedule and other personal projects. You can unassign me if you would like.

**Comment by Mr0grog** [comment]
No worries! Thanks for responding. :)
