### ISSUE TITLE
Build data API

### ISSUE THREAD

**Issue by ldtcooper** [sfbrigade/data-covid19-sfbayarea#6]
Putting this data in the dashboard is going to be a lot easier if we build an API to let it fetch the data we scrape without having to upload that data to the frontend repo.

**Comment by ldtcooper** [comment]
My backend experience is primarily in Ruby on Rails, Node, and Flask. Since we're doing data work here, I would lean towards using Flask for this, but if anyone has strong feelings about that, feel free to chime in!

**Comment by rickpr** [comment]
Are we planning to have any dynamic routes or generate anything on the fly? If we're just updating static files we can serve static files to start instead of building a full-blown API.
